# Populate locally as secrets.yaml (do not commit)
polygon_api_key: "YOUR_POLYGON_API_KEY"
finnhub_api_key: "YOUR_FINNHUB_API_KEY"
alpaca:
  key_id: "YOUR_ALPACA_KEY_ID"
  secret_key: "YOUR_ALPACA_SECRET"

