name: nbsi-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow matplotlib requests

      - name: Run unit tests
        run: |
          python -m unittest discover -s nbsi -p "test_*.py" -v

